### ISSUE TITLE
[Request] Containerize testing

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/dba-multitool#152]
For SQL Server 2017+, look into dockerizing unit testing. This should be faster than relying on Appveyor's individual build images and allow lift and shift to another CI tool later on.

**Comment by LowlyDBA** [comment]
https://github.com/LowlyDBA/dba-multitool/pull/170 is a good first foray into this direction by using TSQLLint via  Github Action. Potentially it makes sense to use Github Actions for some quick-and-dirty tsql smoke tests as a next step.

**Comment by lowlydba** [comment]
Will likely tackle this when SQL Server 2022 comes out and test it on Github runners in parallel with AppVeyor for a bit.

**Comment by lowlydba** [comment]
Won't be using explicit containers anymore, but am in the process of converting to Github runners and using GHA to augment.
