### ISSUE TITLE
[Bug] sp_estindex - rithmetic overflow error converting expression to data type int.

### ISSUE THREAD

**Issue by gflores1023** [LowlyDBA/dba-multitool#155]
**Describe the bug**
I ran this code on my table and received the below error
```
EXEC [sp_estindex] @SchemaName = 'dbo'
				  ,@TableName = 'MyTable'
				  ,@IndexColumns = N'MyField'
				  ,@Verbose = 1
```
	
```
Msg 50000, Level 16, State 2, Procedure sp_estindex, Line 760 [Batch Start Line 0]
[sp_estindex]: Arithmetic overflow error converting expression to data type int.
```		  

Issue is on this line. Since my NumLeafPages: 829971, it overflows @LeafSpaceUsed after multiplying by 8129
`SET @LeafSpaceUsed = 8192 * @NumLeafPages;`

SQL server 2016

Thanks!

**Comment by LowlyDBA** [comment]
Thanks for the bug report! I definitely should've seen this one coming 😁 

I just pushed a quick update to the development branch to use `BIGINT` in most places this might occur. Let me know if that fixes it for you.

**Comment by gflores1023** [comment]
Thanks, latest update worked for me!
