### ISSUE TITLE
[Request] Auto-download latest tSQLt for testing

### ISSUE THREAD

**Issue by LowlyDBA** [LowlyDBA/dba-multitool#165]
Since tSQLt is being actively released again, it makes more sense to start downloading the latest to run tests with. 

This is currently blocked by https://github.com/tSQLt-org/tSQLt/issues/70 which prevents the new version from working with Azure SQL.

**Comment by Octacon100** [comment]
Hi @LowlyDBA -- Do you know if the assembly was ever white listed again? I'm trying to get TSqlT to work with my Azure database and it looks like there's still issues. Have you heard anything about it being whitelisted?

**Comment by LowlyDBA** [comment]
Don't think so. You can use the [previous version here](https://github.com/LowlyDBA/dba-multitool/blob/master/appveyor/install_tsqlt.ps1#L41) to get the working Azure version.
