### ISSUE TITLE
[Request] sp_spaceused <table> output with sp_helpme would be useful

### ISSUE THREAD

**Issue by hellomahesh** [LowlyDBA/dba-multitool#183]
Always wanted to see how much of space used by the table and number for rows in it with <AltF1> cmd

so plugging the output of sp_spaceused <table> as second row in sp_helpme <table> would be a huge helpful..

**Comment by felipeschneider88** [comment]
Hello, Glenn Barry in his Feb'21 release of magic DMV's add this code 

`-- Get Table names, row counts, and compression status for clustered index or heap  (Query 40) (Table Sizes)
SELECT SCHEMA_NAME(o.Schema_ID) AS [Schema Name], OBJECT_NAME(p.object_id) AS [ObjectName], 
SUM(p.Rows) AS [RowCount], data_compression_desc AS [CompressionType]
FROM sys.partitions AS p WITH (NOLOCK)
INNER JOIN sys.objects AS o WITH (NOLOCK)
ON p.object_id = o.object_id
WHERE index_id < 2 --ignore the partitions from the non-clustered index if any
AND OBJECT_NAME(p.object_id) NOT LIKE N'sys%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'spt_%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'queue_%' 
AND OBJECT_NAME(p.object_id) NOT LIKE N'filestream_tombstone%' 
AND OBJECT_NAME(p.object_id) NOT LIKE N'fulltext%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'ifts_comp_fragment%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'filetable_updates%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'xml_index_nodes%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'sqlagent_job%'
AND OBJECT_NAME(p.object_id) NOT LIKE N'plan_persist%'
GROUP BY  SCHEMA_NAME(o.Schema_ID), p.object_id, data_compression_desc
ORDER BY SUM(p.Rows) DESC OPTION (RECOMPILE);`

We can change that to add a where clause with the table like this
`OBJECT_NAME(p.object_id) = @TableName`

**Comment by LowlyDBA** [comment]
Thanks for the suggestion folks.

I'm not sure I see the value in either directly or indirectly combining `sp_spaceused` information into `sp_helpme`, when one can just run the stored procedures back to back to fetch the info. You can always write your own wrapper to call them both if the input is a table, too. 

This stored procedure is intended to be an enhanced version of `sp_help`, not a kitchen sink. If there are parts of `sp_spaceused` that are lacking, creating a new version might be a worthwhile effort, though I haven't found myself wishing it behaved differently to be honest.
