### ISSUE TITLE
[Request] - List of related FK, which link to the current table

### ISSUE THREAD

**Issue by aisbergde** [LowlyDBA/dba-multitool#190]
**Is your feature request related to a problem? Please describe.**

FK are good documented, with a link from the FK to the related column(s)
I would also like so see links from a table to all FK which link to the current table

**Describe the solution you'd like**

an optional  "list of related FK" section after the "Indexes" section

**Describe alternatives you've considered**

**Additional context**

**Comment by LowlyDBA** [comment]
Thanks for the feature suggestion. This was something I originally considered including, but wasn't too sure of its value to people.

This will probably make it into the next non-bug fix release.

**Comment by LowlyDBA** [comment]
Will probably implement this as a "dependency" table, including FKs and user defined object references as well.
