### ISSUE TITLE
[Bug] missing empty line between <details><summary>Click to expand</summary> and list

### ISSUE THREAD

**Issue by aisbergde** [lowlydba/dba-multitool#197]
**Describe the bug**

objects are listed using some 
`<details><summary>Click to expand</summary>`
and a list after

there should be an empty line between this row code and the list, but this empty line is missing.

**To Reproduce**

* create any database documentation
* see the results

**Expected behavior**

empty line before list elements

**Versions(please complete the following information):**

* OS: Windows 10
* SQL Server: 2019
* SSMS: 
*

SQL Server Management Studio						15.0.18369.0
SQL Server Management Objects (SMO)						16.100.46041.41
Microsoft Analysis Services Client Tools						15.0.19342.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19042

**Additional context**

Part of the DBA MultiTool http://dba-multitool.org

Version: 20210412

I just downloaded Version 1.7.2 which documents related FK #190

**Comment by aisbergde** [comment]
Maybe the issue is not related to the procedure but to the way I use it:
I executed in SSMS, results to table, and then just copied the content of all row in the result column. I will try to output as text or to export into a file.

**Comment by aisbergde** [comment]
procedure is OK. But it should not be used with output into grid, but with output as text or direct export into a file.

**Comment by aisbergde** [comment]
no, same issue.

**Comment by LowlyDBA** [comment]
I think this may be more of an issue with how SSMS interprets `CLRF` characters. If you look at the WideWorldImporters sample markdown that is generated by my build process, the line breaks appear fine since it was output using sqlcmd. 

I'll dive in a bit deeper to see if it makes more sense to update the docs/recommended use or change the way line breaks are implemented.

**Comment by aisbergde** [comment]
yes, it is an SSMS issue. I also exported it using sqlcmd and the result is correct. Maybe adding some hint into the documentation could be an idea. I don't remember how I exported in the past. Maybe I never used SSMS but only sqlcmd.

**Comment by LowlyDBA** [comment]
I've opened a [UserVoice bug](https://feedback.azure.com/forums/908035-sql-server/suggestions/43188567-sql-server-management-studio-removing-trailing-crl) regarding this. Please upvote if you agree it should be addressed.

This missing line break does not affect the rendering of the markdown, so is a minor issue. I will hold off on implementing any code changes for now and make note of it in the documentation.

Thanks for bringing it to my attention.
