### ISSUE TITLE
[Bug] sp_helpme & sp_sizeoptimiser SQLSTring & msg Variable Case Sensitivity

### ISSUE THREAD

**Issue by mattcargile** [LowlyDBA/dba-multitool#203]
**Describe the bug**
`sp_helpme` and `sp_sizeoptimizer` have variables without proper casing so deployments to case sensitive collations fail. Correction on [Line](https://github.com/LowlyDBA/dba-multitool/blob/86340ebd68f18df7b228e0c14de65f53df913ffc/sp_helpme.sql#L209) `209` and [Line](https://github.com/LowlyDBA/dba-multitool/blob/86340ebd68f18df7b228e0c14de65f53df913ffc/sp_helpme.sql#L435) `435` within `sp_helpme`. Corrections on [lines](https://github.com/LowlyDBA/dba-multitool/blob/86340ebd68f18df7b228e0c14de65f53df913ffc/sp_sizeoptimiser.sql#L1325-L1330) `1325` through `1330` within sp_sizeoptimiser

**To Reproduce**
`Install-DbaMultiTool` on Case Sensitive Instance/Database

**Expected behavior**
Install should complete

**Versions(please complete the following information):**

* OS: N/A
* SQL Server: N/A
* SSMS: v18

**Additional context**
N/A

**Comment by LowlyDBA** [comment]
Thanks for the bug report and fix! Merged to development and will move to master soon.
