### ISSUE TITLE
[Bug] sp_helpme - Case [name] in all_objects ORDER BY

### ISSUE THREAD

**Issue by mattcargile** [LowlyDBA/dba-multitool#206]
**Describe the bug**
On case sensitive collations, I receive the error message below returned when running `sp_helpme` without an parameters. 
```sql
Msg 209, Level 16, State 1, Line 17
Ambiguous column name 'name'.
```

[This ](https://github.com/mattcargile/dba-multitool/blob/02ecb97adc37631af887cf2f904078f3ade55fb8/sp_helpme.sql#L149)is caused within the `ORDER BY` declaration on the first `SET @SQLString`. `[name]` should be `[Name]`.

**To Reproduce**
Run `sp_helpme` from a CS collation.

**Expected behavior**
I expect to a return of all the objects.

**Versions(please complete the following information):**

* OS: N/A
* SQL Server: SQL Server 2014 ( any CS collation )
* SSMS: v18

**Additional context**
I'm working on the pull request now.

**Comment by LowlyDBA** [comment]
Thanks again for the bug & fix!
