### ISSUE TITLE
[Request] sp_doc - document Schemas

### ISSUE THREAD

**Issue by aisbergde** [LowlyDBA/dba-multitool#210]
**Is your feature request related to a problem? Please describe.**
I use extensive Schema descriptions to explain general logic of the databases.
But Schemas are not included in the generated documentation 

**Describe the solution you'd like**
I would like to see an aditional section containing Schemas and their descriptions.

**Describe alternatives you've considered**
No solution, I would need to extract separately or using other tools.
The tool "elsasoft sqlspec" which I used many years in no more available.

**Additional context**

**Comment by LowlyDBA** [comment]
Thanks for the suggestion @aisbergde! 

This is a good addition to the script. I'll add it to the queue of work.
