### ISSUE TITLE
[Request] sp_helpme - Add Included Columns for INDEX on TABLE

### ISSUE THREAD

**Issue by mattcargile** [lowlydba/dba-multitool#264]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Within the `index_name` , `index_description`, and `index_keys` table output, I'd like to see an `index_includes` or the like column. I see from [this line](https://github.com/lowlydba/dba-multitool/blob/main/sp_helpme.sql#L424) that we are using `sp_helpindex`. I'd assume we would have to implement that output [ourselves](https://www.mssqltips.com/sqlservertip/3450/sql-server-index-report-with-included-columns-storage-and-more-for-all-tables-in-a-database/). With _2017_ support only, we could use `STRING_AGG` to comma delimit the columns. Right now, the procedure does work on 2014 and I'd rather use the[ XML trick](https://stackoverflow.com/a/17591536/14905075) for it. 

Thoughts?

**Describe alternatives you've considered**
My alternative was inspecting the index properties within _SQL Server Management Studio_.

**Additional context**
Here is the output data showing the table.
![image](https://user-images.githubusercontent.com/74641867/210397944-58449f21-333b-4fa7-89de-963fa9d1ed1a.png)

Can try to use `dbatools` , `Get-DbaHelpIndex` as inspiration.

**Comment by lowlydba** [comment]
That seems like a good enhancement, thanks for the suggestion! I won't be able to dig into the approach for a little while, but if in the mean time you want to try a PR feel free to. 

I do want to keep backwards compatibility for any "supported" versions still so XML is a good way to go (though it is sad to write in 2023)
